name: Deploy to VPS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 168.231.106.21
          username: root
          key: |
            b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABB65yx7Xg
            01YihfAD9gqjUYAAAAGAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIDnva4vHqoiHD36m
            AlJMl4KCzFxPIJEfIq10yZUBT8sNAAAAoI6dRxuG/kv+FsWEjl8b15L60cDXa4k3a0dt6I
            tvMht0w1rc24LNeNlRuO48WWyDnMreCXIoP5I5AaB9UAlTY05n3KMe9RhXQK0SOBMDS0/j
            QYdXthQYl7vvGMYPGcxoD1DRdcFI/0XsIOFzUPbLmzUAqovaTVLCjRa0nhFr7OQ8XuBxSZ
            UFcDglBt1PEQG1kkirovaa7UcVCaDTgQ2t/T8=
          port: 22
          # envs: VPS_SSH_KEY
          script: |
            # Naviguer vers le répertoire du projet
            cd /var/www/webapp/issouffadika

            # Sauvegarder l'ancienne version
            if [ -d "current" ]; then
              mv current backup-$(date +%Y%m%d-%H%M%S)
            fi

            # Créer le répertoire de déploiement
            mkdir -p current

            # Cloner le code depuis GitHub
            git clone https://github.com/${{ github.repository }}.git temp-deploy

            # Copier les fichiers nécessaires
            cp -r temp-deploy/* current/
            cp -r temp-deploy/.* current/ 2>/dev/null || true

            # Nettoyer
            rm -rf temp-deploy

            # Naviguer vers le répertoire de déploiement
            cd current

            # Installer les dépendances
            npm ci --production

            # Construire l'application
            npm run build

            # Redémarrer le service PM2
            pm2 restart issouffadika || pm2 start npm --name "issouffadika" -- start

            # Nettoyer les anciennes sauvegardes (garder les 5 plus récentes)
            cd /var/www/webapp/issouffadika
            ls -t backup-* | tail -n +6 | xargs -r rm -rf

            echo "Déploiement terminé avec succès!"
