name: Deploy to VPS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm i

      - name: Build application
        run: npm run build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 168.231.106.21
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/webapp/issouffadika

            if [ -d "current" ]; then
              mv current backup-$(date +%Y%m%d-%H%M%S)
            fi

            mkdir -p current
            git clone https://github.com/${{ github.repository }}.git temp-deploy
            cp -r temp-deploy/* current/
            cp -r temp-deploy/.[!.]* current/ 2>/dev/null || true
            rm -rf temp-deploy

            cd current

            export NODE_ENV=production
            npm ci --production
            npm run build

            if [ ! -d ".next" ]; then
              echo "Erreur: Le build .next n'existe pas!"
              exit 1
            fi

            pm2 stop issouffadika 2>/dev/null || true
            pm2 delete issouffadika 2>/dev/null || true
            lsof -ti:3001 | xargs kill -9 2>/dev/null || true

            pm2 start npm --name "issouffadika" -- start -- -p 3001
            pm2 save

            cd /var/www/webapp/issouffadika
            ls -t backup-* | tail -n +6 | xargs -r rm -rf

            echo "Déploiement terminé avec succès!"
